### ISSUE TITLE
"options.PouchDB is required" in console on page load

### ISSUE THREAD

**Issue by andyjessop** [jakepeyser/hoodie-notes#5]
I've just set up the project as per the instructions on the readme. Server starts fine, visiting localhost:8080, I get a blank screen and the following error message in the console:

```
Uncaught TypeError: options.PouchDB is required (see https://github.com/hoodiehq/hoodie-client#constructor)
    at getState (app.js:47045)
    at new Hoodie (app.js:47021)
    at Object.module.exports (app.js:46988)
    at __webpack_require__ (app.js:20)
    at Object.exports.__esModule (app.js:46922)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:33375)
    at __webpack_require__ (app.js:20)
    at app.js:63
    at app.js:66
```

**Comment by andyjessop** [comment]
Fixed by changing this line: https://github.com/jakepeyser/hoodie-notes/blob/master/src/store/reducers/index.js#L9

to `PouchDB: require('pouchdb-browser').default`

**Comment by gitowiec** [comment]
I got the same issue, @andyjessop thanks for solution.

**Comment by jakepeyser** [comment]
Good catch @andyjessop! Looks like an issue introduced by a recent `pouchdb-browser` update. Updating the code and changed the installation instructions to use yarn to avoid this situation in the future. Thanks for the heads up!
