### ISSUE TITLE
`display: flex`  shouldn't be on `.notes-list` and `.notes-card`

### ISSUE THREAD

**Issue by andyjessop** [jakepeyser/hoodie-notes#6]
If you have display flex on these selectors then the items shrink to fit, making them unreadable when the overall height is too low. If you did keep display flex then you need to set a minimum height.

However, it works best when you just remove display flex.

**Comment by jakepeyser** [comment]
Good suggestion. I didn't think much about about responsiveness for this ditty, but working in a little fix for this issue.
