### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by mike-duran-mitchell** [jakepeyser/hoodie-notes#9]
After installing and running with yarn, there is a 404 for app.js and style.js that prevents the app from working. These files were added into the .gitignore file, and the css-tricks article mentions nothing about these files, so there is no clue what is supposed to be in them.

**Comment by jakepeyser** [comment]
did you run a `yarn build` before starting the app?

**Comment by mike-duran-mitchell** [comment]
Nope. Don't know how I missed that step. That is the reason. Thanks.
